In [2]:
import pandas as pd
import numpy as np
from scipy import stats as st

In [5]:
control=pd.read_csv("control_group.csv")
control.head()

  person_id  recovery_time_hrs
0      C001                4.4
1      C002                4.1
2      C003                3.2
3      C004                4.3
4      C005                4.9

In [6]:
test=pd.read_csv("test_group.csv")

In [7]:
test.head()

  person_id  recovery_time_hrs
0      T001                3.7
1      T002                4.1
2      T003                3.7
3      T004                3.9
4      T005                3.7

In [15]:
control_mean=control.recovery_time_hrs.mean().round(2)
control_std_dev=control.recovery_time_hrs.std().round(2)
control_size=control.shape[0]
control_mean, control_std_dev, control_size

(np.float64(4.0), np.float64(0.48), 130)

In [16]:
test_mean=test.recovery_time_hrs.mean().round(2)
test_std_dev=test.recovery_time_hrs.std().round(2)
test_size=test.shape[0]
test_mean, test_std_dev, test_size

(np.float64(3.91), np.float64(0.32), 100)

In [17]:
a=control_std_dev**2/control_size
b=test_std_dev**2/test_size
z_score=(control_mean-test_mean)/np.sqrt(a+b)
z_score

np.float64(1.701962671923127)

In [18]:
Z_critical=st.norm.ppf(1-0.05)
Z_critical

np.float64(1.6448536269514722)

In [19]:
z_score>Z_critical

np.True_

In [21]:
p_value=1-st.norm.cdf(z_score)
p_value

np.float64(0.0443811829929599)

In [22]:
p_value<0.05

np.True_