## Problem Statement

An e-commerce company is evaluating two different website designs to see which one results in higher customer engagement. Design A is the current design, while Design B incorporates new features aimed at improving user experience. The company hypothesizes that Design B will lead to a higher average time spent on the website by users.

**Datasets:**
- current_design.csv: Contains data for user interactions with the current website design (Design A), with columns user_id and time_spent_minutes.
- new_design.csv: Contains data for user interactions with the new website design (Design B), with columns user_id and time_spent_minutes.

**Objective:**
- To determine whether Design B results in a higher average time spent on the website compared to Design A.

**Steps to perform:**
- Set the null and alternate hypothesis for this analysis.
- Load the datasets current_design.csv and new_design.csv.
- Calculate the mean and standard deviation of the time spent for both designs.
- Determine the sizes of both groups.
- Calculate the z-score to compare the means of both groups.
- Set the significance level (alpha) at 5% for a right-tailed test.
- Calculate the critical z-value for the right-tailed test at the 5% significance level.
- Compare the calculated z-score with the critical z-value to decide whether to reject the null hypothesis.
- Write down your observations in the end.

**Import Necessary Libraries**

In [15]:
import pandas as pd
import numpy as np
from scipy import stats as st

**Define hypothesis**

- Null Hypothesis (H0): Design B does not lead to a higher average time spent on the website compared to Design A (mean_DesignB <= mean_DesignA).
- Alternate Hypothesis (H1): Design B leads to a higher average time spent on the website compared to Design A (mean_DesignB > mean_DesignA).

**1: Load the datasets**

In [16]:

control = pd.read_csv("current_design.csv")
test = pd.read_csv("new_design.csv")

In [17]:
print(control.shape)
control.head()

(100, 2)

  user_id  time_spent_minutes
0    C001                5.93
1    C002                5.21
2    C003                5.07
3    C004                5.06
4    C005                6.33

In [18]:
print(test.shape)
test.head()

(100, 2)

  user_id  time_spent_minutes
0    T001                7.49
1    T002                7.37
2    T003                7.32
3    T004                6.85
4    T005                7.10

**2: Calculate the mean and standard deviation of the time spent for both designs.**

In [19]:
#control statistics

control_mean = control.time_spent_minutes.mean().round(2)
control_std = control.time_spent_minutes.std().round(2)
control_size = control.shape[0]
control_mean, control_std, control_size

(6.02, 0.62, 100)

In [20]:
#test statistics

test_mean = test.time_spent_minutes.mean().round(2)
test_std = test.time_spent_minutes.std().round(2)
test_size = test.shape[0] 
test_mean, test_std, test_size

(8.06, 0.9, 100)

**3: Test using rejection region (i.e. critical z value)**

In [21]:
a = (control_std**2/control_size)
b = (test_std**2/test_size)

Z_score = (test_mean - control_mean)/np.sqrt(a+b)
Z_score

18.66617228956536

In [22]:
# For a significance level of 5% (0.05) in a right-tailed test, the critical Z-value is approximately 1.645

alpha = 0.05 # significance level of 5%

critical_z_value = st.norm.ppf(1 - alpha)  # Right-tailed test at 5% significance level
critical_z_value

1.6448536269514722

In [23]:
Z_score > critical_z_value

True

### Observations and Conclusion

- As you can see above, since the Z score is higher than the critical z value, it falls inside the rejection region. Hence we will reject our null hypothesis and accept the alternate hypothesis that Design B leads to a higher average time spent on the website compared to Design A